//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_User()
        {
            this.SYS_Role = new HashSet<SYS_Role>();
            this.SYS_Program = new HashSet<SYS_Program>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Bu { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Passw { get; set; }
        public string Del { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Role> SYS_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Program> SYS_Program { get; set; }
    }
}
