//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Module
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lv { get; set; }
        public string Controller { get; set; }
        public string View_ { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public Nullable<int> UpId { get; set; }
        public Nullable<int> ProgramId { get; set; }
    }
}
