//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Module()
        {
            this.SYS_Role = new HashSet<SYS_Role>();
            this.SYS_Program = new HashSet<SYS_Program>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Lv { get; set; }
        public string Controller { get; set; }
        public string View_ { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public Nullable<int> UpId { get; set; }
        public Nullable<int> ProgramId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Role> SYS_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Program> SYS_Program { get; set; }
    }
}
